name: arcs-test

services:
  arcs:
    image: ghcr.io/myLogic207/go-arcs/server:latest
    build:
      context: .
      dockerfile: dockerfile.server
    hostname: arcs
    ports:
      - "8080:8080"
    volumes:
      - ./example/mappings.yaml:/tmp/mappings.yaml
      - ./example/remote.alloy:/tmp/remote.alloy
    networks:
      - testnet
